spring:
  profiles:
    active: qa
    
management:
  endpoints:
    web:
      exposure:
        include: "*"  
      base-path: /manage

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
