app:
  loadUser: false
  orderCount: 100000
debug: false

server:
  port: 8222
  
spring:
  datasource:
    username: sa
    password: welcome
    url: jdbc:h2:mem:orders_db
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true
